# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterField(
            model_name='hashtaglist',
            name='hashtag',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
