# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0002_auto_20170928_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='commentary',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
