# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0003_auto_20171003_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
