# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0004_auto_20171007_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
