# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0006_remove_commentary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(max_length=280, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='hashtaglist',
            name='change_time',
            field=models.DateField(auto_now=True),
        ),
    ]
